version: "3.8"

services:
  app:
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    image: php82-fpm-base:1
    volumes:
      - ./:/var/www/app   # ou ./laravel_app
    ports:
      - "5173:5173"
    working_dir: /var/www/app
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - XDEBUG_MODE=debug,develop
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared

  web:
    image: nginx:1.25-alpine
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_net
